version: '3'

services:
  frontend:
    image: 1eshkin/wordcloud-frontend:0.6.0
    ports:
      - 8080:80/tcp

  backend:
    image: 1eshkin/wordcloud-backend:0.5.0
    environment:
      - MAX_WORKERS=1
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - 8080:80/tcp
