version: "3"

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8080:3001
  #   volumes:
  #     - ./frontend/src:/app/src

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8889:8888
    volumes:
      - ./backend/app:/app