version: '3'

services:
  frontend:
    image: 1eshkin/wordcloud-frontend:1.0.6
    ports:
      - 3000:80/tcp

  backend:
    image: 1eshkin/wordcloud-backend:0.5.3
    environment:
      - MAX_WORKERS=1
    volumes:
      - ./logs:/app/logs
    ports:
      - 8080:80/tcp
