FROM python:3.7

COPY ./app /app
COPY ./logs /logs

RUN pip install --no-cache-dir \
    fastapi==0.63.0 \
    uvicorn==0.13.4 \
    spacy==3.1.3 \
    langid==1.1.6 \
    && python -m spacy download en_core_web_sm \
    && python -m spacy download ru_core_news_sm \
    && python -m spacy download fr_core_news_sm \
    && python -m spacy download de_core_news_sm \
    && python -m spacy download es_core_news_sm

EXPOSE 8888

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8888", "--debug"]