curl 'http://localhost:8889/lemmatize' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: http://localhost:8888' \
  -H 'Referer: http://localhost:8888/' \
  -H 'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' \
  --data-binary '{"text": "Зонд «БепиКоломбо» совместной европейско-японской миссии по исследованию Меркурия 1 октября впервые пролетел мимо этой планеты. Он передал первые снимки ее поверхности, на которые попала часть северного полушария Меркурия с кратерами Кальвино и Лермонтов и равниной Сихту. «БепиКоломбо», запущенный в октябре 2018 года, должен выйти на орбиту Меркурия в 2025 году — до этого в рамках своих гравитационных маневров он пролетит мимо планеты шесть раз. После выхода на орбиту «БепиКоломбо» займется изучением состава поверхности Меркурия и его внутренней структуры, а также анализом происхождения магнитного поля и его взаимодействия с солнечным ветром и составлением подробной карты полярных областей планеты. На орбите «БепиКоломбо» проведет около года, после чего миссия будет завершена. "}' \
  --compressed