name: Create and publish a Docker images

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push frontend
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: frontend
      #     push: true
      #     tags: ghcr.io/leshkin/wordcloud-frontend:latest

      # - name: Build and push backend
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: backend
      #     push: true
      #     tags: ghcr.io/leshkin/wordcloud-backend:latest

      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: alexey@wordcloud.online
          ssh_private_key: ${{ secrets.WORDCLOUD_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.WORDCLOUD_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          keep_files: 0
          deploy_path: /wordcloud-test
          stack_file_name: docker-compose.yml
          args: wordcloud