name: Create and publish a Docker images

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: 1eshkin/wordcloud-frontend:0.2.0

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: 1eshkin/wordcloud-backend:0.1.0

      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: alexey@wordcloud.online
          ssh_private_key: ${{ secrets.WORDCLOUD_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.WORDCLOUD_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          keep_files: 1
          deploy_path: /home/alexey/wordcloud
          stack_file_name: docker-compose.yml
          args: wordcloud