name: Lint code base

on:
  push:
    branches: ['main']

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (index.html|d3-cloud.js|sitemap.xml)

  build-and-push-docker-images:
    name: Build, push and deploy Docker images
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: 1eshkin/wordcloud-frontend:0.6.2

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: 1eshkin/wordcloud-backend:0.5.1

      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: alexey@wordcloud.online
          ssh_private_key: ${{ secrets.WORDCLOUD_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.WORDCLOUD_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          keep_files: 5
          deploy_path: /home/alexey/wordcloud
          stack_file_name: docker-compose.yml
          args: wordcloud
