name: Super Linter

on:
  push:
    branches: ['main']

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs the Super-Linter action
      - name: Super-linter
        uses: super-linter/super-linter/slim@v6.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (d3-cloud.js|sitemap.xml|ads.txt)
